services:
  hcokey_bot:
    image: hockey_bot:2.1
    container_name: hockey_bot
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./database/:/TelegramHockeyBotV2/database/:rw
    command: 
      - bash 
      - -c 
      - cd ./TelegramHockeyBotV2 && git init
      - cd ./TelegramHockeyBotV2 && git remote add origin https://github.com/BenFin75/TelegramHockeyBotV2.git
      - cd ./TelegramHockeyBotV2 && git fetch
      - cd ./TelegramHockeyBotV2 && git reset origin/main
      - cd ./TelegramHockeyBotV2 && git checkout -t origin/main
      - cd ./TelegramHockeyBotV2 && python3 ./main
    restart: unless-stopped