services:
  hcokey_bot:
    image: hockey_bot:2.1
    container_name: hockey_bot
    network_mode: host
    env_file:
      - .env
    volumes:
      - /database:/TelegramHockeyBotV2/database:rw
    restart: unless-stopped