services:
  hcokey_bot_testing:
    image: hockey_bot:testing
    container_name: hockey_bot_testing
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./testing-database/:/TelegramHockeyBotV2/database/:rw
    restart: unless-stopped